"""Initial migration

Revision ID: 5b233e4e4577
Revises: 
Create Date: 2025-05-22 21:42:12.274698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b233e4e4577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 